# Default values for serverclient.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of server loadBalancers & deployments
serverInstanceCount: 1
# Number of client deployments 
clientInstanceCount: 1

nameOverride: ""
fullnameOverride: ""
azureRegion: "westeurope"
nodeSelector: 
  kubernetes.io/os: windows


deployment:
  client:
      clientReplicaCount: 1
      clientCommand: ["powershell"]
      requestsArg: 10
      requestDelayArg: 1000
  server:
    serverCommand: ["/server.exe", "-p", "4444", "-swt", "120", "-awt", "150"] # readiness probe failure periodSeconds (30) x failureRetries (3)
    serverReplicaCount: 2
    nodeAffinity: ""
    topologyKey: testtype
  image:
    registry: winnetdockerregistry.azurecr.io
    repository: netconnect
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: WS22vrc0.1
  auth:
    enabled: false
  imagePullSecrets: []
  podAnnotations: {}
  preStopHookCommand: ["curl", "http://127.0.0.1:8090/kill", "-v"]
  clientPreStopHookCommand: ["ping", "-n", "99", "localhost"]
  terminationGracePeriodSeconds: 600
  podSecurityContext: {}
  tolerations: []
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: LoadBalancer
  tcpPort: 4444
  udpPort: 4445
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Local
