{{- range $i, $e := until (int .Values.clientInstanceCount) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ (include "serverclient.fullname" $)}}-client-{{ $i }}
  labels:
    {{- include "serverclient.labels" $ | nindent 4 }}-client-{{ $i }}
  namespace: {{ $.Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ $.Values.deployment.client.clientReplicaCount }}
  selector:
    matchLabels:
      {{- include "serverclient.selectorLabels" $| nindent 6 }}-client-{{ $i }}
  template:
    metadata:
      annotations:
        {{- toYaml $.Values.deployment.podAnnotations | nindent 8 }}
      labels:
        {{- include "serverclient.selectorLabels" $ | nindent 8 }}-client-{{ $i }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.deployment.imagePullSecrets | nindent 8 }}
      securityContext:
        {{- toYaml $.Values.deployment.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      containers:
        - name: {{ $.Chart.Name }}-{{ $i }}
          image: "{{ $.Values.deployment.image.registry }}/{{ $.Values.deployment.image.repository }}:{{ $.Values.deployment.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.deployment.image.pullPolicy }}
          resources:
            {{- toYaml $.Values.deployment.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          lifecycle:
            preStop:
              exec:
                command: 
                {{- toYaml $.Values.deployment.clientPreStopHookCommand | nindent 18 }}
          command: ["powershell"]
          args: ["while($true)", "{ Sleep 5000 }"]
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      terminationGracePeriodSeconds: {{ $.Values.deployment.terminationGracePeriodSeconds }}
      tolerations:
        {{- toYaml $.Values.deployment.tolerations | nindent 8 }}
{{- end }}