{{- range $i, $e := until (int .Values.serverInstanceCount) }}
{{- $svcName := (printf "%s-%d" (include "serverclient.fullname"  $) .) -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  labels:
    {{- (printf "%s-%d" (include "serverclient.labels" $) .) | nindent 4 }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ $svcName }}
spec:
  internalTrafficPolicy: {{ $.Values.service.internalTrafficPolicy }}
  {{- if eq $.Values.service.type "NodePort" }} 
  externalTrafficPolicy: {{ $.Values.service.externalTrafficPolicy }}
  {{- else if eq $.Values.service.type "LoadBalancer" }} 
  externalTrafficPolicy: {{ $.Values.service.externalTrafficPolicy }}
  {{- else }}
  {{- end }}
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: {{ $.Values.service.sessionAffinity }}
  type: {{ $.Values.service.type }}
  ports:
    - name: tcp
      port: 80
      targetPort: {{ $.Values.service.tcpPort }}
      protocol: TCP
    - name: udp
      port: {{ $.Values.service.udpPort }}
      protocol: UDP
      targetPort: {{ $.Values.service.udpPort }}
  selector:
    {{- (printf "%s-%d" (include "serverclient.selectorLabels" $) .) | nindent 4 }}
{{ end }}
